language: node_js
node_js:
  - "18.8.0"

jobs:
  include:
    - stage: NPM RC Release
      if: tag == *-RC*
      node_js: "18.8.0"
      script:
        - npm install
        - npm run build
        - echo "Deploying RC to NPM..."
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_API_KEY
        tag: next
    - stage: NPM Release
      if: tag != *-RC*
      node_js: "18.8.0"
      script:
        - npm install
        - npm run build
        - echo "Deploying to NPM..."
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_API_KEY
        on:
          tags: true